Remake jkrun flags & args to accept multiple args

diff --git a/jkrun b/jkrun
--- a/jkrun
+++ b/jkrun
@@ -18,58 +18,129 @@ function jkmsg() {
     jkpremsg; for i in {1..12}; do printf ' '; done
 }
 
-while getopts 'd:lns:r:' OPTION; do
-    case "$OPTION" in
-    d)
-        # permission check
-        if [[ $(id -u) != 0 ]]; then jkpremsg; printf "${warn}permission denied, are you root?\n"; exit 1; fi
-        
-        requestedcuid=$(ls ${mountpoint} | grep "^${OPTARG}$")
-        if [[ "${requestedcuid}" != "" ]]; then
-            cuid=${OPTARG}
-            umount /var/lib/jkrun/${cuid}/overlay
-            rm -rf "${mountpoint}/${cuid}"
-            jkpremsg; printf "${info}deleted container \"${cuid}\"\n"
-            exit 0
-        else
-            jkpremsg; printf "${warn}not found: unable to find container \"${OPTARG}\"\n"
-            exit 1
-        fi
-        ;;
-    l)
-        jkpremsg; echo "Containers:"
-        containers=$(ls -l ${mountpoint} | grep -Po "[0-9]{4,5}$")
-        for container in ${containers}; do jkmsg; echo "${container}"; done
-        exit 0
-        ;;
-    n)
-        dosetupnetwork="true"
-        ;;
-    s)
-        requestedcuid=$(ls ${mountpoint} | grep "^${OPTARG}$")
-        if [[ "${requestedcuid}" != "" ]]; then
-            cuid=${OPTARG}
-            isnewcontainer="false"
-            jkpremsg; printf "${info}starting container \"${cuid}\"\n"
-        else
-            jkpremsg; printf "${warn}not found: unable to find container \"${OPTARG}\"\n"
-            exit 1
-        fi
-        ;;
-    r) 
-        if [[ "${OPTARG}" != "" ]]; then
-            pathtoimgtar="${OPTARG}"
-        else
-            jkpremsg; printf "${warn}Whoops I need to know where the rootfs is, try something like...\n"
-            jkpremsg; printf "${warn}sudo jkrun ./alpine-minirootfs-3.15.0-x86_64.tar.gz\n"
-            exit 1
-        fi
-        ;;
-    ?)
-        jkpremsg; printf "${warn}usage: jkrun [-l][-r][-s] i.e. sudo jkrun -r path/to/tar\n"
-        exit 0
-        ;;
-    esac
+function permissionCheck() {
+    if [[ $(id -u) != 0 ]]; then 
+        jkpremsg; printf "${warn}permission denied, are you root?\n" 
+        exit 1 
+    fi
+}
+
+argflag=""
+argarray=()
+argspassedarray=($*)
+cmdargs=()
+for arg in $*; do
+    if [[ "${arg:0:1}" == "-" ]]; then
+        for (( i=1; i < ${#arg}; i++ )); do
+            flag=${arg:$i:1}
+            case "${flag}" in
+                r)
+                    if [[ "${arg}" == "${argspassedarray[0]}" ]]; then
+                        if (( $# >= 3 )); then
+                            pathtoimgtar="${argspassedarray[1]}"
+                            cmdtoexec="${argspassedarray[2]}"
+                            for (( a=3; a < $#; a++ )); do
+                                cmdargs+=("${argspassedarray[$a]}")
+                            done
+                            argflag="${flag}"
+                        else
+                            jkpremsg; printf "${warn}the '-${flag}' flag requires 2 args\n"
+                            jkpremsg; printf "${warn}Ex. sudo jkrun -r path/to/tar /bin/sh"
+                            exit 1
+                        fi
+                    else
+                        jkpremsg; printf "${warn}the '-${flag}' must be passed as the first arg"
+                        jkpremsg; printf "${warn}Ex. sudo jkrun -r path/to/tar /bin/sh"
+                        exit 1
+                    fi
+                ;;
+                l)
+                    jkpremsg; echo "Containers:"
+                    containers=$(ls -l ${mountpoint} | grep -Po "[0-9]{4,5}$")
+                    for container in ${containers}; do jkmsg; echo "${container}"; done
+                    exit 0
+                ;;
+                d)
+                    permissionCheck
+                    if [[ "${arg}" == "${argspassedarray[0]}" ]]; then
+                        if (( ${#argspassedarray[@]} >= 2 )); then
+                            for (( d=1; d < $#; d++ )); do
+                                requestedcuid=$(ls ${mountpoint} | grep "^${argspassedarray[$d]}$")
+                                if [[ "${requestedcuid}" != "" ]]; then
+                                    cuid=${requestedcuid}
+                                    ismounted=$(mount | grep /var/lib/jkrun/${cuid}/overlay)
+                                    if [[ "${ismounted}" != "" ]]; then
+                                        umount /var/lib/jkrun/${cuid}/overlay
+                                    fi
+                                    rm -rf "${mountpoint}/${cuid}"
+                                    jkpremsg; printf "${info}deleted container \"${cuid}\"\n"
+                                else
+                                    jkpremsg; printf "${warn}not found: unable to find container '\"${requestedcuid}\"'\n"
+                                fi
+                            done
+                            exit 0
+                        else
+                            jkpremsg; printf "${warn}the '-${flag}' flag requires at least 1 arg\n"
+                            jkpremsg; printf "${warn}Ex. jkrun -d 1234 5678"
+                            exit 1    
+                        fi
+                    else
+                        jkpremsg; printf "${warn}the '-${flag}' must be passed as the first arg"
+                        jkpremsg; printf "${warn}Ex. sudo jkrun -r path/to/tar /bin/sh"
+                        exit 1
+                    fi
+                ;;
+                D)
+                    permissionCheck
+                    for jkcuid in $(ls ${mountpoint}); do
+                        ismounted=$(mount | grep /var/lib/jkrun/${jkcuid}/overlay)
+                        if [[ "${ismounted}" != "" ]]; then
+                            umount /var/lib/jkrun/${jkcuid}/overlay
+                        fi
+                        rm -rf "${mountpoint}/${jkcuid}"
+                        jkpremsg; printf "${info}deleted container \"${jkcuid}\"\n"
+                    done
+                    exit 0
+                ;;
+                n)
+                    dosetupnetwork="true"
+                ;;
+                s)
+                    permissionCheck
+                    if [[ "${arg}" == "${argspassedarray[0]}" ]]; then
+                        if (( ${#argspassedarray[@]} >= 3 )); then
+                            requestedcuid=$(ls ${mountpoint} | grep "^${argspassedarray[1]}$")
+                            if [[ "${requestedcuid}" != "" ]]; then
+                                cmdtoexec="${argspassedarray[2]}"
+                                for (( s=3; s < $#; s++ )); do
+                                    cmdargs+=("${argspassedarray[$s]}")
+                                done
+                                argflag="${flag}"
+                                cuid=${requestedcuid}
+                                isnewcontainer="false"
+                                jkpremsg; printf "${info}starting container \"${cuid}\"\n"
+                            else
+                                jkpremsg; printf "${warn}not found: unable to find container \"${requestedcuid}\"\n"
+                                exit 1
+                            fi
+                        else
+                            jkpremsg; printf "${warn}the '-${flag}' flag requires exactly 1 arg\n"
+                            jkpremsg; printf "${warn}Ex. sudo jkrun -s 1234"
+                            exit 1 
+                        fi
+                    else
+                        jkpremsg; printf "${warn}the '-${flag}' must be passed as the first arg"
+                        jkpremsg; printf "${warn}Ex. sudo jkrun -s 1234"
+                        exit 1
+                    fi
+                ;;
+                *) ;;
+            esac
+        done
+    elif [[ "${arg}" == "${argspassedarray[0]}" ]]; then
+        jkpremsg; printf "${warn}usage: jkrun [-lD][-sdr] i.e. sudo jkrun -r path/to/tar cmd\n"
+        exit 1        
+    fi
 done
 
 conoverlayfs="${mountpoint}/${cuid}"
@@ -169,9 +240,9 @@ chmod +x "${overlaydir}/${netsourcefile}"
 
 # commands to execute inside containerized process
 cmds=(\
+    "mount -t sysfs sysfs /sys" \
     "mount -t proc proc /proc" \
     "############## Begin Setup Cgroups ##############" \
-    "mount -t sysfs sysfs /sys" \
     "mount -t tmpfs cgroup /sys/fs/cgroup" \
     "mkdir /sys/fs/cgroup/memory" \
     "mkdir /sys/fs/cgroup/blkio" \
@@ -219,15 +290,36 @@ cmds=(\
     "if [ ! -d /sys/fs/cgroup/systemd/jkrun ]; then mkdir /sys/fs/cgroup/systemd/jkrun; fi" \
     "cd /sys/fs/cgroup" \
     "echo 1 | tee memory/jkrun/cgroup.procs blkio/jkrun/cgroup.procs cpu,cpuacct/jkrun/cgroup.procs devices/jkrun/cgroup.procs freezer/jkrun/cgroup.procs hugetlb/jkrun/cgroup.procs misc/jkrun/cgroup.procs net_cls,net_prio/jkrun/cgroup.procs perf_event/jkrun/cgroup.procs pids/jkrun/cgroup.procs rdma/jkrun/cgroup.procs > systemd/jkrun/cgroup.procs" \
+    "echo 1000000000 > memory/jkrun/memory.limit_in_bytes" \
+    "echo 100 > pids/jkrun/pids.max" \
     "cd /" \
     "############## End Setup Cgroups ##############" \
     "############## Begin Setup Devices ##############" \
-    "#mkdir /dev/null" \
-    "#mkdir /dev/tty" \
-    "#mount -t devtmpfs"
+    "# mount -t devtmpfs -o nosuid,noexec,relatime,size=1957816k,nr_inodes=489454,mode=755 udev /dev" \
+    "# rm -rf /dev/dri /dev/disk /dev/bsg /dev/block /dev/input /dev/bus /dev/lightnvm" \
+    "# find /dev -type f -regex '/dev/[^cfmnprstuz][a-z]+' -delete" \
+    "# find /dev -regex '/dev/tty[S]?[0-9]+' -delete" \
+    "# mount -t tmpfs dev_tmpfs /dev" \
+    "# ln -s /proc/self/fd/2 /dev/stderr" \
+    "# ln -s /proc/self/fd/0 /dev/stdin" \
+    "# ln -s /proc/self/fd/1 /dev/stdout" \
+    "# ln -s /proc/kcore /dev/core" \
+    "# ln -s /proc/self/fd /dev/fd" \
+    "# mkdir /dev/pts" \
+    "# mount -t devpts -o ptmxmode=666 devpts /dev/pts"
+    "# ln -s /dev/pts/ptmx /dev/ptmx"
+    "# mkdir /dev/mqueue && chmod +xt /dev/mqueue" \
+    "# mount -t mqueue -o nosuid,nodev,noexec,relatime mqueue /dev/mqueue" \
+    "# mkdir /dev/shm && chmod +xt /dev/shm" \
+    "# mount -t tmpfs shm_tmpfs /dev/shm" \
+    "# mknod /dev/null c 1 3 -m 666" \
     "############## End Setup Devices ##############" \
     "hostname jkrun" \
 )
+# /dev/ptmx
+
+# Lunux required device files...
+# full, null, random, tty, urandom, zero
 
 # udev on /dev/null type devtmpfs (rw,nosuid,noexec,relatime,size=1957816k,nr_inodes=489454,mode=755,inode64)
 # udev on /dev/tty type devtmpfs (rw,nosuid,noexec,relatime,size=1957816k,nr_inodes=489454,mode=755,inode64)
@@ -257,4 +349,4 @@ unshare \
     --mount \
     --net \
     --cgroup \
-    chroot "${overlaydir}" /bin/sh -c './'"${sourcefile}"';./'"${netsourcefile}"';printf "\e[0m"; exec /bin/sh'
+    chroot "${overlaydir}" /bin/sh -c './'"${sourcefile}"';./'"${netsourcefile}"';printf "\e[0m"; exec '"${cmdtoexec} ${cmdargs[@]}"
